conda-forge/nipype-feedstock

- .travis.yml
- README.md
- appveyor.yml
- ci_support/run_docker_build.sh
- recipe/meta.yaml
Related PR ( https://github.com/conda-forge/nipype-feedstock/pull/1 ). Fixes Python dependency and re-renders. Bumps build number.
> Fix python

- recipe/meta.yaml
This is currently using a specific branch on my fork of nipype - Once everything is all set I'll change the URL
> Release 0.14.0

- recipe/meta.yaml
> fix: remove "v" prefix from version

- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.1.0           |
* URL = https://github.com/nipy/nipype/archive/rel/1.1.0.tar.gz
* SHA256 = `1c2bf68684659864185dd9813c6e8a5dbf0b4c1822c17adadcfc6ec77cbeabff`
> [WIP] REL: 1.1.0

- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.5.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.5.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/win_python2.7.yaml
- .ci_support/win_python3.5.yaml
- .ci_support/win_python3.6.yaml
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.1.1           |
* URL = https://github.com/nipy/nipype/archive/rel/1.1.1.tar.gz
* SHA256 = `85397aa716498c3cdb3a141a6cc4934bf846723ac9b446231979c3e0a58fdea1`
> REL: 1.1.1

- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.5.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.5.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/win_python2.7.yaml
- .ci_support/win_python3.5.yaml
- .ci_support/win_python3.6.yaml
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.1.2           |
* URL = https://github.com/nipy/nipype/archive/rel/1.1.2.tar.gz
* SHA256 = `61575119a0bfd3687523551bc5ebbe0e5a25450f606c01e169bb3cc5d44930d9`
> REL: 1.1.2

- .appveyor.yml
- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.5.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.5.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/win_python2.7.yaml
- .ci_support/win_python3.5.yaml
- .ci_support/win_python3.6.yaml
- .circleci/build_steps.sh
- .circleci/fast_finish_ci_pr_build.sh
- .circleci/run_docker_build.sh
- .travis.yml
- recipe/LICENSE
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.1.3           |
* URL = https://github.com/nipy/nipype/archive/rel/1.1.3.tar.gz
* SHA256 = `9b44997b4ca531ca2f68ac9e9d09a3aab903048eab3286355c252afb09f6b29b`
> REL: 1.1.3

- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.1.4           |
* URL = https://github.com/nipy/nipype/archive/rel/1.1.4.tar.gz
* SHA256 = `534bce705ec6692019050a331634b48ecc25225f5dae91d42c84c4a4729facbb`
> REL: 1.1.4

- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.1.5           |
* URL = https://github.com/nipy/nipype/archive/rel/1.1.5.tar.gz
* SHA256 = `63d6ce7305ac1711122c4a046cea79c25cd180957f8a09a570dad1618f024735`
> REL: 1.1.5

- .appveyor.yml
- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .azure-pipelines/build_steps.sh
- .azure-pipelines/run_docker_build.sh
- .travis.yml
- README.md
- azure-pipelines.yml
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.1.7           |
* URL = https://github.com/nipy/nipype/archive/rel/1.1.7.tar.gz
* SHA256 = `a75b9063ad0922d4d22e619ca39e42b72126e8e6fdbc2cefd0e99acaeb1e0cc4`
> REL: 1.1.7

- .appveyor.yml
- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.1.9           |
* URL = https://github.com/nipy/nipype/archive/rel/1.1.9.tar.gz
* SHA256 = `6576cddfdb7f3f3666d8391dcc3fef67622ead0870a2ac9c7e5ab885e90ed7b9`
> REL: 1.1.9

- .appveyor.yml
- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .azure-pipelines/run_docker_build.sh
- .gitattributes
- README.md
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.2.2           |
* URL = https://github.com/nipy/nipype/archive/rel/1.2.2.tar.gz
* SHA256 = `aaae83cd8d4f37751911bb374c531e2254b8b75df0b65f42459b61a6c282d425`
> REL: 1.2.2

- recipe/meta.yaml
| `CIRCLE_BRANCH`           |            |
| `CIRCLE_TAG`              | 1.3.1              |
* URL = https://github.com/nipy/nipype/archive/1.3.1.tar.gz
* SHA256 = `5f3e6e26b5dd609f1b78791718bcf22cbebc6195d4dafeacae51c07b46d5278a`
---
> REL: 1.3.1

- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.4.1           |
* URL = https://github.com/nipy/nipype/archive/rel/1.4.1.tar.gz
* SHA256 = `0b641fe7fbf7382722484692f1ff2fa56cd1d116676d372024662f4b9110b7db`
---
> REL: 1.4.1

- README.md
- recipe/meta.yaml
| `CIRCLE_BRANCH`           |            |
| `CIRCLE_TAG`              | 1.3.2              |
* URL = https://github.com/nipy/nipype/archive/1.3.2.tar.gz
* SHA256 = `4cf7345b25ad504e6f6c6e8297206d250e91fd4c961f6992592bfe541b8322e0`
---
> REL: 1.3.2

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.4.2           |
* URL = https://github.com/nipy/nipype/archive/rel/1.4.2.tar.gz
* SHA256 = `f5c7da9eb784c33ede95654a962e415973b81ac1f5b61b3a42cfa3e10ed5dfc4`
---
> [WIP] REL: 1.4.2

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_python3.6.____cpython.yaml
- .ci_support/linux_python3.7.____cpython.yaml
- .ci_support/linux_python3.8.____cpython.yaml
- .ci_support/osx_python3.6.____cpython.yaml
- .ci_support/osx_python3.7.____cpython.yaml
- .ci_support/osx_python3.8.____cpython.yaml
- .ci_support/win_python3.6.____cpython.yaml
- .ci_support/win_python3.7.____cpython.yaml
- .ci_support/win_python3.8.____cpython.yaml
- README.md
- recipe/meta.yaml
| `CIRCLE_BRANCH`           |            |
| `CIRCLE_TAG`              | 1.5.0rc1              |
* URL = https://github.com/nipy/nipype/archive/1.5.0rc1.tar.gz
* SHA256 = `e8e0c15fadf9a6ffc1dc0a53c1d5610601e976816a61f86b2eed84505de9da92`
---
> REL: 1.5.0rc1

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.6.____cpython.yaml
- .ci_support/osx_64_python3.7.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- .ci_support/win_64_python3.6.____cpython.yaml
- .ci_support/win_64_python3.7.____cpython.yaml
- .ci_support/win_64_python3.8.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- azure-pipelines.yml
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.5.1           |
* URL = https://github.com/nipy/nipype/archive/rel/1.5.1.tar.gz
* SHA256 = `b249b0861816f04212d71d60cda8f8d1157093353055e5ee1098520164c9585b`
---
> REL: 1.5.1

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.6.0           |
* URL = https://github.com/nipy/nipype/archive/rel/1.6.0.tar.gz
* SHA256 = `50a3e5c59d696333606f1c2d9541c1be125660811f72a64de3595135abae384b`
---
> REL: 1.6.0

- .azure-pipelines/azure-pipelines-win.yml
- .circleci/config.yml
- recipe/meta.yaml
| `CIRCLE_BRANCH`           |            |
| `CIRCLE_TAG`              | 1.8.2              |
* URL = https://github.com/nipy/nipype/archive/1.8.2.tar.gz
* SHA256 = `a7d978dc44573ebdd7b05ef1daea64383066c66bfc7f9cdea88c1d5456531129`
---
> REL: 1.8.2

- .azure-pipelines/azure-pipelines-win.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- build-locally.py
- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.8.3           |
* URL = https://github.com/nipy/nipype/archive/rel/1.8.3.tar.gz
* SHA256 = `e53174b671b95c6192737098debe24c82ff918ced0b57caf164c65099349e6da`
---
> REL: 1.8.3

- recipe/meta.yaml
| `CIRCLE_BRANCH`           | rel/1.8.5           |
* URL = https://github.com/nipy/nipype/archive/rel/1.8.5.tar.gz
* SHA256 = `f0aa0a3212cb1057cac86aba805c2aad89d0dccdc65d4f23522d14d74b6187b4`
---
> REL: 1.8.5

- .gitignore
- recipe/meta.yaml
> fix: Add acres to dependencies
